throwErrorOnExtraParameters: true
transparentTileErrorColor: "rgba(78, 78, 255, 125)"
opaqueTileErrorColor: "rgba(255, 155, 155, 0)"
jdbcDrivers:
    - org.postgresql.Driver
templates:
  A4 portrait: !template
    reportTemplate: report.jrxml
    jdbcUser: "{DB_USER}"
    jdbcPassword: "{DB_PASSWORD}"
    jdbcUrl: "jdbc:postgresql://{DB_HOST}:{DB_PORT}/{DB_NAME}"
    attributes:
      id: !integer
        default: null
      criterio_punto_inicial: !integer
        default: 1
      title: !string
        default: "CERTIFICADO PLANO PREDIAL CATASTRAL"
      datasetName: !string
        default: null
      map: !map
        maxDpi: 400
        width: 540
        height: 400
        zoomLevels: !zoomLevels
            scales: [100, 200, 300, 500, 1000, 2000, 2500, 3000, 5000, 7500, 10000, 15000, 20000, 25000, 50000, 100000, 500000]
      scalebar: !scalebar
        width: 180
        height: 20
        default:
          align: "right"
          fontSize: 8
          subIntervals: true
      northArrowDef: !northArrow
        size: 40
        default:
          graphic: "file://images/NorthArrow.svg"
      overviewMap: !overviewMap
        width: 265
        height: 215
        maxDpi: 400
        style: "file:///styles/bbox.sld"
        zoomSnapTolerance: 0.025
        zoomLevelSnapStrategy: CLOSEST_LOWER_SCALE_ON_TIE
        zoomLevels: !zoomLevels
          scales: [ 100, 200, 300, 500, 1000, 2000, 2500, 3000, 5000, 7500, 10000, 15000, 20000, 25000, 50000, 100000, 500000, 1000000 ]
      overlayLayers: !staticLayers
        default:
          layers:
            - type: "grid"
              unitFormat: " %s"
              formatGroupingSeparator: "."
              valueFormat: "###,###"
              renderAsSvg: true
              rotateLabels: false
              numberOfLines: [3, 3]
              labelColor: "#000000"
              haloColor: "#ffffff"
              haloRadius: 1
              horizontalYOffset: 7
              font:
                size: 5
                name: ["Arial", "Helvetica", "Nimbus Sans L", "Liberation Sans", "FreeSans", "Sans-serif"]
              style:
                version: 2
                "*":
                    symbolizers:
                    - type: line
                      strokeDashstyle: "solid"
                      strokeWidth: 0.3
                      strokeColor: "#3c3c3c"
                      strokeOpacity: 0.5
      overviewOverlayLayers: !staticLayers
        default:
          layers:
            - type: "grid"
              unitFormat: " %s"
              formatGroupingSeparator: "."
              valueFormat: "###,###"
              rotateLabels: false
              numberOfLines: [2, 2]
              labelColor: "#000000"
              haloColor: "#ffffff"
              haloRadius: 1
              font:
                size: 4
                name: ["Arial", "Helvetica", "Nimbus Sans L", "Liberation Sans", "FreeSans", "Sans-serif"]
              style:
                version: 2
                "*":
                    symbolizers:
                    - type: line
                      strokeDashstyle: "solid"
                      strokeWidth: 0.3
                      strokeColor: "#3c3c3c"
                      strokeOpacity: 0.5
    processors:
    - !addBackgroundLayers
      inputMapper:
          overlayLayers: staticLayers
          map: map
    - !addBackgroundLayers
      inputMapper:
          overviewOverlayLayers: staticLayers
          overviewMap: map
    - !reportBuilder
      directory: '.'
    - !createMap
      inputMapper:
        map: map
      outputMapper:
        mapSubReport: mapSubReport1
        mapContext: mapContext1
    - !createOverviewMap {}
    - !createScalebar
      inputMapper:
        scalebar: scalebar
        mapContext1: mapContext
      outputMapper:
        scalebarSubReport: scalebarSubReport1
    - !createNorthArrow
      inputMapper:
        northArrowDef: northArrow
      outputMapper:
        northArrowSubReport: northArrowSubReport1
