throwErrorOnExtraParameters: true
transparentTileErrorColor: "rgba(78, 78, 255, 125)"
opaqueTileErrorColor: "rgba(255, 155, 155, 0)"
jdbcDrivers:
    - org.postgresql.Driver
templates:
  A4 portrait: !template
    reportTemplate: report.jrxml
    jdbcUser: "postgres"
    jdbcPassword: "secret"
    jdbcUrl: "jdbc:postgresql://host:port/database"
    attributes:
      id: !integer
        default: null
      criterio_punto_inicial: !integer
        default: 2
      title: !string
        default: "CERTIFICADO PLANO PREDIAL CATASTRAL"
      map: !map
        maxDpi: 400
        width: 540
        height: 400
        zoomLevels: !zoomLevels
            scales: [100, 200, 300, 500, 1000, 2000, 2500, 3000, 5000, 7500, 10000, 15000, 20000, 25000, 50000, 100000, 500000]
      overviewMap: !overviewMap
        width: 265
        height: 215
        maxDpi: 400
        zoomFactor: 20
      overlayLayers: !staticLayers
        default:
          layers:
            - type: "grid"
              unitFormat: " %s"
              formatGroupingSeparator: "."
              valueFormat: "###,###"
              rotateLabels: false
              numberOfLines: [3, 3]
              labelColor: "#000000"
              haloColor: "#ffffff"
              haloRadius: 1
              horizontalYOffset: 7
              font:
                size: 5
                name: ["Arial", "Helvetica", "Nimbus Sans L", "Liberation Sans", "FreeSans", "Sans-serif"]
              style:
                version: 2
                "*":
                    symbolizers:
                    - type: line
                      strokeDashstyle: "solid"
                      strokeWidth: 0.3
                      strokeColor: "#3c3c3c"
                      strokeOpacity: 0.5      
            - type: "WMS"
              imageFormat: "image/png"
              baseURL: "https://ide.proadmintierra.info/geoserver/ladm_col_2_2_1/wms"
              customParams: 
                TRANSPARENT: true
              layers: ["ladm_col_2_2_1:la_palma_terreno"]
              styles: ["terreno_no_fill_ppc"]
              opacity: 1
            - type: "WMS"
              imageFormat: "image/png"
              baseURL: "https://ide.proadmintierra.info/geoserver/ladm_col_2_2_1/wms"
              customParams: 
                TRANSPARENT: true
              layers: ["ladm_col_2_2_1:la_palma_construccion"]
              opacity: 1
      overviewOverlayLayers: !staticLayers
        default:
          layers:
            - type: "grid"
              unitFormat: " %s"
              formatGroupingSeparator: "."
              valueFormat: "###,###"
              rotateLabels: false
              numberOfLines: [2, 2]
              labelColor: "#000000"
              haloColor: "#ffffff"
              haloRadius: 1
              font:
                size: 4
                name: ["Arial", "Helvetica", "Nimbus Sans L", "Liberation Sans", "FreeSans", "Sans-serif"]
              style:
                version: 2
                "*":
                    symbolizers:
                    - type: line
                      strokeDashstyle: "solid"
                      strokeWidth: 0.3
                      strokeColor: "#3c3c3c"
                      strokeOpacity: 0.5
            - type: "WMS"
              imageFormat: "image/png"
              baseURL: "https://ide.proadmintierra.info/geoserver/ladm_col_2_2_1/wms"
              customParams: 
                TRANSPARENT: true
              layers: ["ladm_col_2_2_1:la_palma_terreno"]
              styles: ["terreno_no_fill_overview_ppc"]
              opacity: 1
    processors:
    - !addBackgroundLayers
      inputMapper:
          overlayLayers: staticLayers
          map: map
    - !addBackgroundLayers
      inputMapper:
          overviewOverlayLayers: staticLayers
          overviewMap: map
    - !reportBuilder
      directory: '.'
    - !createMap
      inputMapper:
        map: map
      outputMapper:
        mapSubReport: mapSubReport1
        mapContext: mapContext1
    - !createOverviewMap {}
